language: node_js
node_js:
- '4'
sudo: false
branches:
  only:
  - master
  - gh-pages
  - backup-2015-mozfest-app
script:
- echo "Nothing to build, no tests to run"
notifications:
  irc: irc.mozilla.org#communityops
deploy:
- provider: s3
  access_key_id: AKIAJPLHUYJHYHPM7HYQ
  secret_access_key:
    secure: "XYbdOcVLHs1RPU7URJ2IieN8W0C+5wexr3zupNBcjgHiZLIuT7KaYKW1q6SVnJ1475Vk303YIZnKOsuxBaVC/ZidaQnczHz86+1oCWR7d6kyZoswtaIo/z4mJ/jbQH9o9oLyuMcFC001Lz+4q5JMjbB5NtV0Db1vbLO00FArGfjm+ZF2j0UrItH9IcRjyWJPVOABzsikrtZ9rAAIgXleW6mvRRjAmbzxnYMflhbcX3BZMJvf8dKp2MuyImJVY83oHO9QdkEjiQ6XG7+d6cOAefSYRWU7VV1QPF2h7H7U9mewz7pCtM5bgxFyJx1wq+diQ1IJQRcmassyyu7XjkG7JxNJjfOeFQ36QLiRD7cD9nqAdi7aV8ybecgmlzXjAP013eWsz7hZX+yYlHBchQmVzDCnqZULWdTE4h6d2VWZzehqGNgWQNwQZyVZ39uwy3prsJ4OM++JK8Vf0QRszl4mtad6lLhvcXk49OyX0NQnW2EVz2vUgXcV1stQPakXm9kx0G7r+9nwsJ+b52UM6nz9zVsAnsrLMZ3VAe0sEm9SuWPvRwyBNIfGoiBLumSguueA+wyoKTTNu3BU0iXxBNbSk2f5bPjPG7fWiaRAvd8IVmGV0UPUIfSdqLw/n41G0BYiwBOryK+8fzacu0BSYHTvAPd8VV2alFfjVQc60ZzA/cM="
  bucket: mozfest-schedule-production-s3bucket-te3i6be2idig
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: mozilla/mozfest-event-app
    branch: backup-2015-mozfest-app
